from __future__ import annotations

import json
import math
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from sklearn.metrics import accuracy_score, average_precision_score, confusion_matrix, f1_score, precision_score, recall_score, roc_auc_score


ROOT = Path(__file__).resolve().parents[1]
PYTHON_RUNTIME_NOTE = "Generated by scripts/complete_project_audit_pack.py"

REPORT_AUDIT_DIR = ROOT / "reports" / "feature_audit"
DOC_ANALYSIS_DIR = ROOT / "docs" / "analysis"
BUSINESS_CHART_DIR = DOC_ANALYSIS_DIR / "business_insight_selected_charts"
V3_PACKAGE_DIR = ROOT / "docs" / "version 3" / "stacking_model_v3"

CLEAN_DATA = ROOT / "data" / "processed" / "clean_dataset.csv"


def ensure_dirs() -> None:
    for path in [
        REPORT_AUDIT_DIR,
        DOC_ANALYSIS_DIR,
        BUSINESS_CHART_DIR,
        V3_PACKAGE_DIR / "models",
        V3_PACKAGE_DIR / "data",
        V3_PACKAGE_DIR / "reports",
        V3_PACKAGE_DIR / "scripts",
        V3_PACKAGE_DIR / "docs",
        V3_PACKAGE_DIR / "images",
    ]:
        path.mkdir(parents=True, exist_ok=True)


def register_font() -> str:
    candidates = [
        Path("C:/Windows/Fonts/tahoma.ttf"),
        Path("C:/Windows/Fonts/THSarabunNew.ttf"),
        Path("C:/Windows/Fonts/arial.ttf"),
    ]
    for font_path in candidates:
        if font_path.exists():
            pdfmetrics.registerFont(TTFont("AuditFont", str(font_path)))
            return "AuditFont"
    return "Helvetica"


FONT_NAME = register_font()


def styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "AuditTitle",
            parent=base["Title"],
            fontName=FONT_NAME,
            fontSize=20,
            leading=26,
            alignment=TA_CENTER,
            spaceAfter=14,
        ),
        "h1": ParagraphStyle(
            "AuditH1",
            parent=base["Heading1"],
            fontName=FONT_NAME,
            fontSize=15,
            leading=20,
            spaceBefore=12,
            spaceAfter=8,
        ),
        "h2": ParagraphStyle(
            "AuditH2",
            parent=base["Heading2"],
            fontName=FONT_NAME,
            fontSize=12,
            leading=16,
            spaceBefore=8,
            spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "AuditBody",
            parent=base["BodyText"],
            fontName=FONT_NAME,
            fontSize=9.5,
            leading=14,
            alignment=TA_LEFT,
            spaceAfter=5,
        ),
        "small": ParagraphStyle(
            "AuditSmall",
            parent=base["BodyText"],
            fontName=FONT_NAME,
            fontSize=8,
            leading=11,
            alignment=TA_LEFT,
        ),
    }


S = styles()


def p(text: Any, style: str = "body") -> Paragraph:
    safe = str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    safe = safe.replace("\n", "<br/>")
    return Paragraph(safe, S[style])


def make_table(rows: list[list[Any]], widths: list[float] | None = None, repeat_rows: int = 1) -> Table:
    table = Table([[p(cell, "small") for cell in row] for row in rows], colWidths=widths, repeatRows=repeat_rows)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#263238")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, -1), FONT_NAME),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cfd8dc")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7f9fa")]),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def markdown_table(df: pd.DataFrame) -> str:
    headers = [str(col) for col in df.columns]
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for _, row in df.iterrows():
        values = [str(row[col]) for col in df.columns]
        lines.append("| " + " | ".join(value.replace("\n", " ") for value in values) + " |")
    return "\n".join(lines)


def build_pdf(title: str, output: Path, story: list[Any]) -> None:
    doc = SimpleDocTemplate(
        str(output),
        pagesize=A4,
        rightMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
        title=title,
    )
    doc.build(story)


@dataclass
class Insight:
    name: str
    chart: Path
    insight: str
    reason: str
    features: list[str]
    action: str


def existing_chart(path: str) -> Path:
    return ROOT / path


BUSINESS_INSIGHTS = [
    Insight(
        "Customer return history",
        existing_chart("reports/Graph Item/eda_customer_history.png"),
        "ประวัติการคืนของลูกค้าเป็นสัญญาณหลักของ return-risk เพราะสะท้อนพฤติกรรมซ้ำรายบุคคล",
        "เลือกเพราะเชื่อมกับโจทย์ order ที่ 3 โดยใช้ order ก่อนหน้าเท่านั้น เช่น 1/2 = 0.5",
        ["hist_order_count", "hist_return_rate", "customer_return_ratio", "cust_return_rate_30d", "cust_return_rate_180d"],
        "ใช้จัดระดับความเสี่ยงก่อนยืนยันหรือจัดส่ง และใช้ทำ Feature Store รายลูกค้า",
    ),
    Insight(
        "Category and payment interaction",
        existing_chart("reports/Graph Item/cross_chart_category_payment.png"),
        "สินค้าบาง category เมื่อจับคู่กับ payment method บางแบบมี return rate สูงกว่าเฉลี่ย",
        "เลือกเพราะช่วยให้ model เห็น interaction ไม่ใช่ดู category หรือ payment แบบแยกกัน",
        ["category", "payment_method", "category_payment", "is_cod"],
        "ใช้เพิ่ม rule/feature สำหรับ COD หรือ category ที่เสี่ยงสูง",
    ),
    Insight(
        "Category and channel interaction",
        existing_chart("reports/Graph Item/cross_chart_category_channel.png"),
        "ช่องทางขายบางช่องทำให้ความเสี่ยงต่างกัน แม้เป็นสินค้าหมวดเดียวกัน",
        "เลือกเพราะ channel สะท้อนพฤติกรรมซื้อและความตั้งใจซื้อ เช่น TV/TikTok/App",
        ["category", "channel_type", "category_channel", "preferred_channel"],
        "ใช้จัด workflow confirm order แยกตาม channel",
    ),
    Insight(
        "Province and payment risk",
        existing_chart("reports/Graph Item/cross_chart_province_payment.png"),
        "พื้นที่และ payment method มีผลร่วมกับ risk จาก logistics และพฤติกรรมชำระเงิน",
        "เลือกเพราะ province เป็นตัวแทน operational context เช่น พื้นที่ไกลหรือพื้นที่มีปัญหาคืนสูง",
        ["province", "payment_method", "province_payment"],
        "ใช้ให้ทีม operation เฝ้ากลุ่มจังหวัด/ช่องทางชำระเงินที่มี risk สูง",
    ),
    Insight(
        "Product rating threshold",
        existing_chart("docs/version 2/reports/eda_v2/v2_rating_threshold.png"),
        "rating ต่ำมีความสัมพันธ์กับโอกาสคืนสินค้า เพราะสะท้อนคุณภาพสินค้าและความคาดหวังลูกค้า",
        "เลือกเพราะสร้าง feature binary ได้ง่ายและอธิบายเชิงธุรกิจชัด",
        ["product_rating", "low_rating_alert"],
        "ใช้ flag สินค้าที่ควรตรวจคุณภาพหรือให้ข้อมูลสินค้าเพิ่มก่อนขาย",
    ),
    Insight(
        "Promotion and discount behavior",
        existing_chart("docs/version 2/reports/eda_v2/v2_promotion_pattern.png"),
        "discount/promotion สูงอาจดึงดูด impulse purchase และเพิ่มโอกาสคืน",
        "เลือกเพราะมีข้อมูลก่อน order เข้าและใช้กับ real-time scoring ได้",
        ["promo_type", "promo_discount_rate", "total_discount_pct", "discount_amount_ratio", "is_high_discount"],
        "ใช้แยก order ที่เกิดจาก promotion แรงเพื่อประเมิน risk เพิ่ม",
    ),
    Insight(
        "Price and basket amount",
        existing_chart("docs/version 2/reports/eda_v2/v2_price_pattern.png"),
        "ราคา จำนวน และยอดรวม order สะท้อนแรงจูงใจและผลกระทบด้าน cost",
        "เลือกเพราะเป็นข้อมูลพื้นฐานที่รู้ตอน order เข้าและสัมพันธ์กับ expected loss",
        ["unit_price", "quantity", "total_amount", "log_unit_price", "log_total_amount"],
        "ใช้ประกอบ threshold/cost matrix เมื่อ order มูลค่าสูง",
    ),
    Insight(
        "Logistics expected risk",
        existing_chart("reports/Graph Item/eda_logistics_expected.png"),
        "เวลา delivery ที่คาดไว้ courier และ damage rate ช่วยบอกความเสี่ยงก่อนเกิดการส่งจริง",
        "เลือกเฉพาะ feature ที่รู้ก่อนส่งสินค้า ส่วน delivery_days/delay_days เป็น post-event ต้องแยกใช้",
        ["courier_type", "avg_delivery_days", "delivery_time_expected_days", "damage_rate", "logistics_risk"],
        "ใช้กับ order-time model โดยไม่ใช้ข้อมูลอนาคต",
    ),
    Insight(
        "Repurchase behavior",
        existing_chart("reports/Graph Relation Feature/relation_repurchase_risk.png"),
        "การซื้อซ้ำสินค้าหรือหมวดเดิมช่วยบอก familiarity และลด/เพิ่มความเสี่ยงตามพฤติกรรม",
        "เลือกเพราะเป็น signal ที่คำนวณจาก history ลูกค้าได้แบบ point-in-time",
        ["is_repurchased_item", "days_since_last_order"],
        "ใช้ประกอบ customer history เพื่อประเมินความมั่นใจของ order ใหม่",
    ),
    Insight(
        "Order time and weekend",
        existing_chart("reports/Graph Item/eda_hour_trend.png"),
        "ชั่วโมงสั่งซื้อและ weekend สะท้อนบริบทการซื้อ เช่น impulse หรือ campaign traffic",
        "เลือกเพราะต้นทุน query ต่ำและรู้ได้ทันทีตอน order เข้า",
        ["order_hour", "order_dayofweek", "is_weekend"],
        "ใช้เป็น feature เสริม ไม่ควรเป็นตัวหลักถ้า performance ไม่เพิ่ม",
    ),
]


def copy_business_charts() -> list[dict[str, Any]]:
    rows = []
    for idx, insight in enumerate(BUSINESS_INSIGHTS, start=1):
        chart_exists = insight.chart.exists()
        target = ""
        if chart_exists:
            suffix = insight.chart.suffix.lower()
            target_path = BUSINESS_CHART_DIR / f"{idx:02d}_{insight.name.lower().replace(' ', '_')}{suffix}"
            shutil.copy2(insight.chart, target_path)
            target = str(target_path.relative_to(ROOT))
        rows.append(
            {
                "no": idx,
                "insight": insight.name,
                "source_chart": str(insight.chart.relative_to(ROOT)) if insight.chart.exists() else str(insight.chart),
                "copied_chart": target,
                "chart_found": chart_exists,
                "business_insight": insight.insight,
                "reason_selected": insight.reason,
                "mapped_features": ", ".join(insight.features),
                "model_or_business_action": insight.action,
            }
        )
    return rows


def write_business_insight_report(rows: list[dict[str, Any]]) -> None:
    out_csv = REPORT_AUDIT_DIR / "business_insight_feature_mapping.csv"
    pd.DataFrame(rows).to_csv(out_csv, index=False, encoding="utf-8-sig")

    md_lines = [
        "# Business Insight + Feature Mapping Summary",
        "",
        "รายงานนี้คัด insight จากชุดกราฟ EDA ที่มีอยู่ในโปรเจ็กต์ โดยเลือกเฉพาะกราฟที่ผูกกับ feature engineering และ model decision ได้จริง",
        "",
        f"- จำนวนกราฟ EDA ทั้งหมดที่ตรวจใน reports/business_insights, reports/Graph Item, reports/Graph Relation Feature: 45 รูป",
        f"- จำนวน insight ที่คัดเลือกมาทำ feature mapping: {len(rows)} ชุด",
        f"- Output chart folder: `{BUSINESS_CHART_DIR.relative_to(ROOT)}`",
        "",
        "| No | Insight | Chart | Feature ที่ตามมา | เหตุผลที่เลือก | สิ่งที่เอาไปใช้ |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        md_lines.append(
            f"| {row['no']} | {row['insight']} | `{row['copied_chart'] or row['source_chart']}` | {row['mapped_features']} | {row['reason_selected']} | {row['model_or_business_action']} |"
        )
    md_lines.extend(
        [
            "",
            "## Leakage Note",
            "",
            "- Feature ที่รู้หลังเหตุการณ์ เช่น `delivery_days`, `delay_days`, `return_date`, `refund_amount`, `return_reason`, `risk_score`, `risk_tier`, `shap_values` ไม่ควรใช้กับ real-time order-time model",
            "- ถ้าใช้ feature กลุ่ม post-delivery ต้องระบุว่าเป็น model สำหรับ post-delivery scoring หรือ experiment เท่านั้น",
        ]
    )
    (DOC_ANALYSIS_DIR / "business_insight_feature_summary.md").write_text("\n".join(md_lines), encoding="utf-8")

    story = [p("Business Insight + Feature Mapping Summary", "title")]
    story.append(p("คัดเลือกกราฟที่เชื่อมกับ feature engineering และ business action ได้จริงจากกราฟ EDA ทั้งหมด 45 รูป", "body"))
    summary_rows = [["No", "Insight", "Feature", "Reason", "Action"]]
    for row in rows:
        summary_rows.append([row["no"], row["insight"], row["mapped_features"], row["reason_selected"], row["model_or_business_action"]])
    story.append(make_table(summary_rows, widths=[1.0 * cm, 3.1 * cm, 4.2 * cm, 4.0 * cm, 4.2 * cm]))
    story.append(PageBreak())
    for row in rows:
        story.append(p(f"{row['no']}. {row['insight']}", "h1"))
        if row["copied_chart"]:
            img_path = ROOT / row["copied_chart"]
            story.append(Image(str(img_path), width=16.0 * cm, height=8.5 * cm, kind="proportional"))
            story.append(Spacer(1, 0.15 * cm))
        story.append(p(f"Insight: {row['business_insight']}", "body"))
        story.append(p(f"เหตุผลที่เลือก: {row['reason_selected']}", "body"))
        story.append(p(f"Feature ที่ตามมา: {row['mapped_features']}", "body"))
        story.append(p(f"Model/Business action: {row['model_or_business_action']}", "body"))
        story.append(Spacer(1, 0.2 * cm))
    build_pdf("Business Insight Feature Summary", DOC_ANALYSIS_DIR / "business_insight_feature_summary.pdf", story)


def manual_return_rate_check() -> None:
    df = pd.read_csv(CLEAN_DATA, low_memory=False)
    df["is_returned"] = pd.to_numeric(df["is_returned"], errors="coerce").fillna(0).astype(int)
    df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
    grouped = (
        df.groupby("customer_id", dropna=False)
        .agg(
            customer_name=("customer_name", "first"),
            total_orders=("order_id", "count"),
            return_count=("is_returned", "sum"),
            first_order_date=("order_date", "min"),
            last_order_date=("order_date", "max"),
        )
        .reset_index()
    )
    grouped["no_return_count"] = grouped["total_orders"] - grouped["return_count"]
    grouped["manual_return_rate"] = grouped["return_count"] / grouped["total_orders"]
    grouped["manual_return_rate_pct"] = grouped["manual_return_rate"] * 100

    mixed = grouped[(grouped["total_orders"] >= 2) & (grouped["return_count"] > 0) & (grouped["no_return_count"] > 0)]
    if len(mixed) >= 10:
        sample = mixed.sample(10, random_state=42)
    else:
        sample = grouped[grouped["total_orders"] >= 2].sample(min(10, len(grouped)), random_state=42)
    sample = sample.sort_values(["total_orders", "return_count", "customer_id"], ascending=[False, False, True]).copy()

    detail_rows = []
    summary_rows = []
    for _, row in sample.iterrows():
        customer_id = row["customer_id"]
        orders = df[df["customer_id"].eq(customer_id)].sort_values(["order_date", "order_id"]).copy()
        order_ids = orders["order_id"].astype(str).tolist()
        returned_order_ids = orders.loc[orders["is_returned"].eq(1), "order_id"].astype(str).tolist()
        no_return_order_ids = orders.loc[orders["is_returned"].eq(0), "order_id"].astype(str).tolist()
        summary_rows.append(
            {
                "customer_id": customer_id,
                "customer_name": row["customer_name"],
                "total_orders": int(row["total_orders"]),
                "return_count": int(row["return_count"]),
                "no_return_count": int(row["no_return_count"]),
                "manual_formula": f"{int(row['return_count'])}/{int(row['total_orders'])}",
                "manual_return_rate": round(float(row["manual_return_rate"]), 6),
                "manual_return_rate_pct": round(float(row["manual_return_rate_pct"]), 2),
                "first_order_date": row["first_order_date"],
                "last_order_date": row["last_order_date"],
                "sample_order_ids": ", ".join(order_ids[:12]),
                "returned_order_ids": ", ".join(returned_order_ids[:12]),
                "no_return_order_ids": ", ".join(no_return_order_ids[:12]),
                "excel_check_note": "return_count / total_orders เช่น 4/8 = 0.5 = 50%",
            }
        )
        prior_orders = 0
        prior_returns = 0
        for _, order in orders.iterrows():
            calc_rate = prior_returns / prior_orders if prior_orders else 0.0
            dataset_hist_count = pd.to_numeric(pd.Series([order.get("hist_order_count", np.nan)]), errors="coerce").iloc[0]
            dataset_hist_rate = pd.to_numeric(pd.Series([order.get("hist_return_rate", np.nan)]), errors="coerce").iloc[0]
            detail_rows.append(
                {
                    "customer_id": customer_id,
                    "order_id": order["order_id"],
                    "order_date": order["order_date"],
                    "current_order_is_returned": int(order["is_returned"]),
                    "manual_prior_order_count": prior_orders,
                    "manual_prior_return_count": prior_returns,
                    "manual_prior_return_rate": round(calc_rate, 6),
                    "dataset_hist_order_count": dataset_hist_count,
                    "dataset_hist_return_rate": dataset_hist_rate,
                    "hist_count_match": bool(prior_orders == dataset_hist_count) if not pd.isna(dataset_hist_count) else "",
                    "hist_rate_abs_diff": round(abs(calc_rate - dataset_hist_rate), 8) if not pd.isna(dataset_hist_rate) else "",
                    "formula_note": f"{prior_returns}/{prior_orders} = {calc_rate:.4f}" if prior_orders else "0 prior orders => 0",
                }
            )
            prior_orders += 1
            prior_returns += int(order["is_returned"])

    pd.DataFrame(summary_rows).to_csv(REPORT_AUDIT_DIR / "customer_return_rate_manual_check.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame(detail_rows).to_csv(REPORT_AUDIT_DIR / "customer_return_rate_order_level_check.csv", index=False, encoding="utf-8-sig")


def load_feature_names_from_joblib(path: Path) -> list[str]:
    if not path.exists():
        return []
    data = joblib.load(path)
    names = data.get("feature_names", [])
    return list(names)


def read_csv_columns(path: Path) -> list[str]:
    if not path.exists():
        return []
    return list(pd.read_csv(path, nrows=5, low_memory=False).columns)


def version_feature_inventory() -> tuple[pd.DataFrame, pd.DataFrame]:
    clean_cols = read_csv_columns(CLEAN_DATA)
    v1_engineered = read_csv_columns(ROOT / "docs" / "version 1" / "data" / "features" / "df_engineered.csv")
    v1_used = load_feature_names_from_joblib(ROOT / "docs" / "version 1" / "data" / "features" / "train_test_sets.pkl")
    v2_engineered = read_csv_columns(ROOT / "docs" / "version 2" / "data" / "features" / "df_engineered_v2_preview.csv")
    v2_used = read_csv_columns(ROOT / "docs" / "version 2" / "reports" / "model_evaluation" / "v2_used_features.csv")
    if v2_used and v2_used[0] == "feature":
        v2_used = pd.read_csv(ROOT / "docs" / "version 2" / "reports" / "model_evaluation" / "v2_used_features.csv")["feature"].tolist()
    v2_xgb_used = pd.read_csv(ROOT / "docs" / "version 2" / "v2_xgboost_safe_plus_rolling" / "data" / "v2_xgboost_safe_plus_rolling_used_features.csv")["feature"].tolist()
    v3_used = load_feature_names_from_joblib(ROOT / "docs" / "version 2" / "data" / "features" / "train_test_sets_v2.pkl")
    v4_engineered = read_csv_columns(ROOT / "docs" / "version 4" / "data" / "features" / "df_engineered_v4_generated.csv")
    v4_used = pd.read_csv(ROOT / "docs" / "version 4" / "reports" / "model_evaluation" / "v4_used_features.csv")["feature"].tolist()

    versions = [
        ("clean_dataset", "clean/raw usable dataset", clean_cols, []),
        ("v1_engineered", "V1 engineered before model encoding", v1_engineered, v1_used),
        ("v1_model_used", "V1 encoded model feature set", v1_used, v1_used),
        ("v2_engineered", "V2 engineered preview before training", v2_engineered, v2_used),
        ("v2_model_used", "V2 model feature set", v2_used, v2_used),
        ("v2_xgboost_safe_plus_rolling", "V2 order-time-safe XGBoost rolling feature set", v2_xgb_used, v2_xgb_used),
        ("v3_stacking", "V3 stacking reuses V2 model feature set", v3_used, v3_used),
        ("v4_generated_engineered", "V4 generated engineered dataset", v4_engineered, v4_used),
        ("v4_generated_model_used", "V4 generated model feature set", v4_used, v4_used),
    ]

    inventory_rows = []
    summary_rows = []
    clean_set = set(clean_cols)
    leakage_cols = {
        "return_id",
        "return_date",
        "return_reason",
        "return_scenario",
        "item_condition",
        "return_status",
        "refund_amount",
        "score_id",
        "risk_score",
        "risk_tier",
        "scored_at",
        "shap_values",
    }
    post_delivery_cols = {"delivery_date", "delivery_days", "delay_days"}
    id_cols = {"order_id", "customer_id", "product_id", "supplier_id", "courier_id", "promo_id", "customer_name", "customer_phone"}

    for version, description, cols, used in versions:
        col_set = set(cols)
        used_set = set(used)
        dropped_from_this = sorted(col_set - used_set) if used else []
        created = sorted(col_set - clean_set)
        retained = sorted(col_set & clean_set)
        risky = sorted(col_set & leakage_cols)
        post_delivery = sorted(col_set & post_delivery_cols)
        ids = sorted(col_set & id_cols)
        summary_rows.append(
            {
                "version": version,
                "description": description,
                "feature_count": len(cols),
                "used_feature_count": len(used_set) if used else "",
                "created_feature_count_vs_clean": len(created),
                "retained_clean_feature_count": len(retained),
                "dropped_or_not_used_count": len(dropped_from_this),
                "leakage_or_target_related_fields": ", ".join(risky),
                "post_delivery_fields": ", ".join(post_delivery),
                "identifier_fields": ", ".join(ids),
                "note": version_note(version),
            }
        )
        for col in cols:
            inventory_rows.append(
                {
                    "version": version,
                    "feature": col,
                    "in_clean_dataset": col in clean_set,
                    "created_by_engineering": col not in clean_set,
                    "used_for_model": col in used_set if used else "",
                    "risk_type": feature_risk_type(col, leakage_cols, post_delivery_cols, id_cols),
                    "feature_group": feature_group(col),
                }
            )
    inventory = pd.DataFrame(inventory_rows)
    summary = pd.DataFrame(summary_rows)
    inventory.to_csv(REPORT_AUDIT_DIR / "feature_inventory_by_version.csv", index=False, encoding="utf-8-sig")
    summary.to_csv(REPORT_AUDIT_DIR / "feature_audit_summary_by_version.csv", index=False, encoding="utf-8-sig")
    return inventory, summary


def version_note(version: str) -> str:
    notes = {
        "clean_dataset": "ฐานข้อมูล clean หลังรวม order/return/customer/product แต่ยังมี post-event/leakage fields ต้องตัดก่อน train",
        "v1_engineered": "มี feature engineering จำนวนมากและ one-hot/encoding ทำให้ final feature count สูง",
        "v1_model_used": "ใช้ encoded features 136 ตัว เหมาะเป็น baseline experiment",
        "v2_engineered": "ลด feature ให้ตีความง่ายขึ้นและใช้ feature history/customer/product/logistics",
        "v2_model_used": "V2 baseline 38 features แต่ยังมี delivery_days/delay_days จึงไม่ order-time safe",
        "v2_xgboost_safe_plus_rolling": "ตัด post-delivery fields และเพิ่ม rolling history 30/60/90/180/365d เหมาะกับ Feature Store",
        "v3_stacking": "ไม่ได้สร้าง feature ใหม่เอง ใช้ V2 feature set แล้วเปลี่ยน model เป็น stacking ensemble",
        "v4_generated_engineered": "ใช้ synthetic/generated data สำหรับทดลอง imbalance/SMOTE/Optuna",
        "v4_generated_model_used": "feature set จาก generated pipeline ไม่ควรเทียบ production โดยตรงกับข้อมูลจริง",
    }
    return notes.get(version, "")


def feature_risk_type(col: str, leakage_cols: set[str], post_delivery_cols: set[str], id_cols: set[str]) -> str:
    if col == "is_returned":
        return "target"
    if col in leakage_cols:
        return "leakage/post-return"
    if col in post_delivery_cols:
        return "post-delivery"
    if col in id_cols:
        return "identifier/query-only"
    return "usable_or_engineered"


def feature_group(col: str) -> str:
    patterns = [
        ("customer_history", ["hist_", "cust_", "days_since_last", "return_ratio", "orders_before", "returns_before"]),
        ("category_product", ["category", "brand", "product", "fragile", "rating"]),
        ("payment_channel", ["payment", "channel", "cod"]),
        ("promotion_discount", ["promo", "discount", "campaign", "tier_discount"]),
        ("logistics", ["courier", "delivery", "delay", "damage", "logistics"]),
        ("location_profile", ["province", "gender", "age", "membership", "tenure"]),
        ("time", ["hour", "month", "dayofweek", "weekend", "date"]),
        ("amount_price", ["price", "amount", "quantity", "spend"]),
        ("target_or_return", ["return", "refund", "risk", "shap", "score"]),
    ]
    low = col.lower()
    for group, keys in patterns:
        if any(key in low for key in keys):
            return group
    return "other"


def evaluate_v1_model() -> dict[str, Any] | None:
    model_path = ROOT / "docs" / "version 1" / "model" / "best_model.pkl"
    data_path = ROOT / "docs" / "version 1" / "data" / "features" / "train_test_sets.pkl"
    if not model_path.exists() or not data_path.exists():
        return None
    model = joblib.load(model_path)
    data = joblib.load(data_path)
    x_test = data["X_test"]
    y_test = data["y_test"]
    proba = model.predict_proba(x_test)[:, 1]
    pred = (proba >= 0.5).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_test, pred, labels=[0, 1]).ravel()
    return {
        "version": "V1",
        "model": type(model).__name__,
        "threshold": 0.5,
        "accuracy": accuracy_score(y_test, pred),
        "recall": recall_score(y_test, pred, zero_division=0),
        "precision": precision_score(y_test, pred, zero_division=0),
        "f1": f1_score(y_test, pred, zero_division=0),
        "auc": roc_auc_score(y_test, proba),
        "avg_precision": average_precision_score(y_test, proba),
        "cost": fn * 150 + fp * 50,
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp),
        "rating": rating(accuracy_score(y_test, pred), recall_score(y_test, pred, zero_division=0), f1_score(y_test, pred, zero_division=0), fn * 150 + fp * 50),
        "note": "computed from packaged V1 model and test set",
    }


def rating(acc: float, recall: float, f1: float, cost: float) -> str:
    if acc >= 0.80 and f1 >= 0.60 and recall >= 0.60 and cost <= 20000:
        return "A"
    if acc >= 0.68 and f1 >= 0.52 and recall >= 0.60 and cost <= 28000:
        return "B+"
    if acc >= 0.65 and f1 >= 0.48 and recall >= 0.55:
        return "B"
    if acc >= 0.60 and f1 >= 0.42:
        return "C"
    return "D"


def model_version_summary() -> pd.DataFrame:
    rows = []
    v1 = evaluate_v1_model()
    if v1:
        rows.append(v1)

    v2_summary = ROOT / "docs" / "version 2" / "model_evaluation_v2" / "v2_test_prediction_summary.csv"
    if v2_summary.exists():
        v2 = pd.read_csv(v2_summary)
        row = v2[v2["scenario"].eq("default_threshold_0_50")].iloc[0].to_dict()
        rows.append(
            {
                "version": "V2 baseline",
                "model": "V2 tuned model",
                "threshold": row["threshold"],
                "accuracy": row["accuracy"],
                "recall": row["recall"],
                "precision": row["precision"],
                "f1": row["f1"],
                "auc": row["auc"],
                "avg_precision": "",
                "cost": row["cost"],
                "tn": row["tn"],
                "fp": row["fp"],
                "fn": row["fn"],
                "tp": row["tp"],
                "rating": rating(row["accuracy"], row["recall"], row["f1"], row["cost"]),
                "note": "baseline V2 default threshold",
            }
        )

    v2_xgb = ROOT / "docs" / "version 2" / "v2_xgboost_safe_plus_rolling" / "reports" / "v2_xgboost_safe_plus_rolling_metrics.csv"
    if v2_xgb.exists():
        row = pd.read_csv(v2_xgb).iloc[0].to_dict()
        rows.append(
            {
                "version": "V2 XGBoost safe rolling",
                "model": "XGBClassifier",
                "threshold": row["selected_threshold"],
                "accuracy": row["accuracy"],
                "recall": row["recall"],
                "precision": row["precision"],
                "f1": row["f1"],
                "auc": row["auc"],
                "avg_precision": row["avg_precision"],
                "cost": row["cost"],
                "tn": row["tn"],
                "fp": row["fp"],
                "fn": row["fn"],
                "tp": row["tp"],
                "rating": row["performance_rating"],
                "note": "order-time safe plus rolling customer history",
            }
        )

    v3_metrics = ROOT / "docs" / "version 3" / "model_evaluation_v3" / "metrics_summary_v3.csv"
    if v3_metrics.exists():
        row = pd.read_csv(v3_metrics).iloc[0].to_dict()
        total = row["tn"] + row["fp"] + row["fn"] + row["tp"]
        acc = (row["tn"] + row["tp"]) / total
        cost = row["fn"] * 150 + row["fp"] * 50
        rows.append(
            {
                "version": "V3 stacking",
                "model": row["model_name"],
                "threshold": row["threshold"],
                "accuracy": acc,
                "recall": row["recall"],
                "precision": row["precision"],
                "f1": row["f1_score"],
                "auc": row["auc_roc"],
                "avg_precision": row["avg_precision"],
                "cost": cost,
                "tn": row["tn"],
                "fp": row["fp"],
                "fn": row["fn"],
                "tp": row["tp"],
                "rating": rating(acc, row["recall"], row["f1_score"], cost),
                "note": "stacking model reusing V2 train/test features",
            }
        )

    v4_metrics = ROOT / "docs" / "version 4" / "reports" / "model_evaluation" / "v4_generated_model_metrics.csv"
    if v4_metrics.exists():
        row = pd.read_csv(v4_metrics).iloc[0].to_dict()
        rows.append(
            {
                "version": "V4 generated",
                "model": row["model"],
                "threshold": row["threshold"],
                "accuracy": row["accuracy"],
                "recall": row["recall"],
                "precision": row["precision"],
                "f1": row["f1"],
                "auc": row["auc"],
                "avg_precision": row["avg_precision"],
                "cost": row["cost_thb"],
                "tn": row["tn"],
                "fp": row["fp"],
                "fn": row["fn"],
                "tp": row["tp"],
                "rating": rating(row["accuracy"], row["recall"], row["f1"], row["cost_thb"]),
                "note": "synthetic/generated data with SMOTE/Optuna",
            }
        )

    out = pd.DataFrame(rows)
    out.to_csv(REPORT_AUDIT_DIR / "model_version_completion_summary.csv", index=False, encoding="utf-8-sig")
    return out


def write_feature_audit_report(inventory: pd.DataFrame, summary: pd.DataFrame, model_summary: pd.DataFrame) -> None:
    manual_path = REPORT_AUDIT_DIR / "customer_return_rate_manual_check.csv"
    order_path = REPORT_AUDIT_DIR / "customer_return_rate_order_level_check.csv"
    manual_rows = pd.read_csv(manual_path).head(10)

    md_lines = [
        "# Feature Audit & Manual Validation",
        "",
        "รายงานนี้เติมส่วนที่ขาดจาก requirement: cross-check return rate รายลูกค้า, compare clean vs engineered features, และสรุป feature/model แต่ละ version",
        "",
        "## Manual Customer Return Rate Check",
        "",
        f"- Summary CSV: `{manual_path.relative_to(ROOT)}`",
        f"- Order-level point-in-time CSV: `{order_path.relative_to(ROOT)}`",
        "- สูตรที่ใช้: `return_count / total_orders` เช่น `4 / 8 = 0.5 = 50%`",
        "- สำหรับ order-level history ใช้เฉพาะ order ก่อนหน้าเท่านั้น ไม่รวม order ปัจจุบัน",
        "",
        markdown_table(manual_rows[["customer_id", "total_orders", "return_count", "manual_formula", "manual_return_rate", "manual_return_rate_pct"]]),
        "",
        "## Feature Summary by Version",
        "",
        markdown_table(summary),
        "",
        "## Model Summary",
        "",
        markdown_table(model_summary[["version", "model", "accuracy", "recall", "precision", "f1", "auc", "cost", "rating", "note"]]),
        "",
        "## Key Findings",
        "",
        "- V2 baseline เป็น version ที่ครบที่สุดบนข้อมูลจริง ทั้ง feature engineering, evaluation, SHAP, threshold และ prediction output",
        "- V2 XGBoost safe rolling เป็น candidate ที่เหมาะกว่าเมื่อจะใช้จริงแบบ order-time เพราะตัด `delivery_days` และ `delay_days` แล้ว",
        "- V3 มี model process แล้ว แต่ feature engineering ไม่ได้แยกเอง ใช้ feature/split จาก V2",
        "- V4 ครบ end-to-end มากที่สุดในเชิง pipeline แต่เป็น synthetic/generated data จึงควรระบุให้ชัดเวลานำเสนอ",
        "- Feature ที่เป็น identifier เช่น `customer_id`, `order_id` ควรใช้สำหรับ query/audit ไม่ควรส่งเข้า model ให้จำ identity โดยตรง",
        "- Feature หลังเหตุการณ์ เช่น return/refund/risk_score/shap_values ต้อง drop ก่อน train เพื่อกัน leakage",
    ]
    (DOC_ANALYSIS_DIR / "feature_audit_and_validation.md").write_text("\n".join(md_lines), encoding="utf-8")

    story = [p("Feature Audit & Manual Validation", "title")]
    story.append(p("สรุปการตรวจ clean_dataset.csv เทียบกับ engineered/model features และ manual return-rate check รายลูกค้า", "body"))
    story.append(p("Manual Return Rate Sample", "h1"))
    manual_table_rows = [["customer_id", "orders", "returns", "formula", "rate", "percent"]]
    for _, row in manual_rows.iterrows():
        manual_table_rows.append(
            [
                row["customer_id"],
                int(row["total_orders"]),
                int(row["return_count"]),
                row["manual_formula"],
                f"{row['manual_return_rate']:.4f}",
                f"{row['manual_return_rate_pct']:.2f}%",
            ]
        )
    story.append(make_table(manual_table_rows, widths=[3.0 * cm, 2.0 * cm, 2.0 * cm, 2.0 * cm, 2.0 * cm, 2.2 * cm]))
    story.append(p("Feature Summary by Version", "h1"))
    summary_rows = [["version", "features", "used", "created", "leakage", "post-delivery", "note"]]
    for _, row in summary.iterrows():
        summary_rows.append(
            [
                row["version"],
                row["feature_count"],
                row["used_feature_count"],
                row["created_feature_count_vs_clean"],
                row["leakage_or_target_related_fields"],
                row["post_delivery_fields"],
                row["note"],
            ]
        )
    story.append(make_table(summary_rows, widths=[3.2 * cm, 1.5 * cm, 1.3 * cm, 1.5 * cm, 3.0 * cm, 2.4 * cm, 4.0 * cm]))
    story.append(PageBreak())
    story.append(p("Model Summary", "h1"))
    model_rows = [["version", "model", "accuracy", "recall", "f1", "auc", "cost", "rating"]]
    for _, row in model_summary.iterrows():
        model_rows.append(
            [
                row["version"],
                row["model"],
                f"{float(row['accuracy']):.2%}",
                f"{float(row['recall']):.2%}",
                f"{float(row['f1']):.2%}",
                f"{float(row['auc']):.2%}",
                f"{int(row['cost']):,}",
                row["rating"],
            ]
        )
    story.append(make_table(model_rows, widths=[3.0 * cm, 4.0 * cm, 2.0 * cm, 2.0 * cm, 2.0 * cm, 2.0 * cm, 2.0 * cm, 1.5 * cm]))
    story.append(p("Key Findings", "h1"))
    for bullet in md_lines[-6:]:
        story.append(p(bullet.replace("- ", ""), "body"))
    build_pdf("Feature Audit and Validation", DOC_ANALYSIS_DIR / "feature_audit_and_validation.pdf", story)


def package_v3(model_summary: pd.DataFrame) -> None:
    source_files = {
        ROOT / "docs" / "version 3" / "best_model_v3_stack.pkl": V3_PACKAGE_DIR / "models" / "best_model_v3_stack.pkl",
        ROOT / "docs" / "version 3" / "model_training_v3_stacking.py": V3_PACKAGE_DIR / "scripts" / "model_training_v3_stacking.py",
        ROOT / "docs" / "version 3" / "model_evaluation_v3.py": V3_PACKAGE_DIR / "scripts" / "model_evaluation_v3.py",
        ROOT / "docs" / "version 3" / "model_evaluation_v3" / "metrics_summary_v3.csv": V3_PACKAGE_DIR / "reports" / "metrics_summary_v3.csv",
        ROOT / "docs" / "version 3" / "model_evaluation_v3" / "threshold_scenarios_v3.csv": V3_PACKAGE_DIR / "reports" / "threshold_scenarios_v3.csv",
        ROOT / "docs" / "version 3" / "model_evaluation_v3" / "accuracy_recall_tradeoff.png": V3_PACKAGE_DIR / "images" / "accuracy_recall_tradeoff.png",
        ROOT / "docs" / "version 2" / "data" / "features" / "train_test_sets_v2.pkl": V3_PACKAGE_DIR / "data" / "train_test_sets_v3_from_v2.pkl",
    }
    for src, dst in source_files.items():
        if src.exists():
            shutil.copy2(src, dst)

    v3_features = load_feature_names_from_joblib(ROOT / "docs" / "version 2" / "data" / "features" / "train_test_sets_v2.pkl")
    pd.DataFrame({"feature": v3_features}).to_csv(V3_PACKAGE_DIR / "data" / "v3_used_features.csv", index=False, encoding="utf-8-sig")

    v3 = model_summary[model_summary["version"].eq("V3 stacking")]
    v3_row = v3.iloc[0].to_dict() if not v3.empty else {}
    runtime_note = "V3 model file exists. Loading may require catboost package because the StackingClassifier contains CatBoostClassifier."
    (V3_PACKAGE_DIR / "reports" / "runtime_validation_note.txt").write_text(runtime_note, encoding="utf-8")
    readme = f"""# Version 3 - Stacking Model Package

## Summary

V3 เป็น model experiment ที่ใช้ feature/split จาก V2 แล้วเปลี่ยน model architecture เป็น Stacking Ensemble

- Base models: `XGBoost`, `LightGBM`, `CatBoost`
- Meta learner: `LogisticRegression`
- Feature source: `train_test_sets_v2.pkl`
- Feature count: `{len(v3_features)}`
- Model file: `models/best_model_v3_stack.pkl`

## Metrics

| Metric | Value |
| --- | ---: |
| Accuracy | {float(v3_row.get('accuracy', 0)):.2%} |
| Recall | {float(v3_row.get('recall', 0)):.2%} |
| Precision | {float(v3_row.get('precision', 0)):.2%} |
| F1 | {float(v3_row.get('f1', 0)):.2%} |
| AUC | {float(v3_row.get('auc', 0)):.2%} |
| Cost | {int(v3_row.get('cost', 0)):,} |
| Rating | {v3_row.get('rating', '')} |

## Process

1. Load `train_test_sets_v2.pkl`
2. Train `XGBClassifier`, `LGBMClassifier`, `CatBoostClassifier`
3. Combine predictions with `StackingClassifier`
4. Use `LogisticRegression(class_weight='balanced')` as meta learner
5. Evaluate threshold scenarios and cost matrix

## Important Note

V3 ไม่ได้สร้าง feature engineering ใหม่เอง แต่ reuse V2 feature set ดังนั้นในรายงานควรอธิบายว่า V3 คือ model architecture experiment ไม่ใช่ feature version ใหม่
"""
    (V3_PACKAGE_DIR / "README.md").write_text(readme, encoding="utf-8")
    (V3_PACKAGE_DIR / "docs" / "v3_stacking_model_process_report.md").write_text(readme, encoding="utf-8")

    story = [p("Version 3 - Stacking Model Process", "title")]
    for line in readme.splitlines():
        if line.startswith("# "):
            continue
        if line.startswith("## "):
            story.append(p(line.replace("## ", ""), "h1"))
        elif line.strip():
            story.append(p(line, "body"))
    img = V3_PACKAGE_DIR / "images" / "accuracy_recall_tradeoff.png"
    if img.exists():
        story.append(PageBreak())
        story.append(p("Accuracy vs Recall Trade-off", "h1"))
        story.append(Image(str(img), width=16.0 * cm, height=9.0 * cm, kind="proportional"))
    build_pdf("V3 Stacking Model Process", V3_PACKAGE_DIR / "docs" / "v3_stacking_model_process_report.pdf", story)


def main() -> None:
    ensure_dirs()
    business_rows = copy_business_charts()
    write_business_insight_report(business_rows)
    manual_return_rate_check()
    inventory, summary = version_feature_inventory()
    model_summary = model_version_summary()
    write_feature_audit_report(inventory, summary, model_summary)
    package_v3(model_summary)

    outputs = [
        DOC_ANALYSIS_DIR / "business_insight_feature_summary.md",
        DOC_ANALYSIS_DIR / "business_insight_feature_summary.pdf",
        REPORT_AUDIT_DIR / "business_insight_feature_mapping.csv",
        REPORT_AUDIT_DIR / "customer_return_rate_manual_check.csv",
        REPORT_AUDIT_DIR / "customer_return_rate_order_level_check.csv",
        REPORT_AUDIT_DIR / "feature_inventory_by_version.csv",
        REPORT_AUDIT_DIR / "feature_audit_summary_by_version.csv",
        REPORT_AUDIT_DIR / "model_version_completion_summary.csv",
        DOC_ANALYSIS_DIR / "feature_audit_and_validation.md",
        DOC_ANALYSIS_DIR / "feature_audit_and_validation.pdf",
        V3_PACKAGE_DIR / "README.md",
        V3_PACKAGE_DIR / "docs" / "v3_stacking_model_process_report.pdf",
    ]
    print(PYTHON_RUNTIME_NOTE)
    for output in outputs:
        print(output.relative_to(ROOT))


if __name__ == "__main__":
    main()
